server:
  port: 8088
location: E:\Projects\twohands
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/twohand2
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/,classpath:/static/assets/,file:${location}
  # 文件上传
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射，可以在实体类中使用驼峰式命名法映射数据库中含下划线的字段
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#pagehelper:
#  helper-dialect: mysql
mybatis: